project: 
  type: website
  render: 
    - "*.qmd"
    - "!CONTRIBUTING.md"
  
website:
  title: "Intermediate ggplot2 workshop series"
  repo-url: "https://github.com/cct-datascience/ggplot2-workshop-series"
  repo-actions: ["source", "issue"]
  sidebar: 
    style: "docked"
    search: true
    logo: logo.png
    contents:
      - "index.qmd"
      - section: "Upcoming series"
        href: "2024/index.qmd"
        contents:
          - "2024/01-foundations/index.qmd"
          - "2024/02-design/index.qmd"
          - "2024/03-extensions/index.qmd"
      - section: "2023"
        contents:
          - "2023/01-foundations/index.qmd"
          - "2023/02-publication-quality-figs/index.qmd"
          - "2023/03-extensions/index.qmd"

format:
  html: 
  #defaults for all html
    code-link: true
    code-copy: true
  uaz-revealjs:
   #defaults for all uaz-revealjs slides
    code-copy: true
    slide-number: true
    chalkboard: true
    mouse-wheel: false
    link-external-icon: true
    link-external-newwindow: true
    logo: "./logo.png"
    footer: "[CCT Data Science ggplot2 workshop series](index.qmd)"
    
execute:
  freeze: auto
  
editor: 
  markdown: 
    wrap: sentence
  