project: 
  type: website
  render: 
    - "*.qmd"
    - "!CONTRIBUTING.md"
  resources:
    - 2024/02-data-comm/script.R
  
website:
  title: "Intermediate ggplot2 workshop series"
  repo-url: "https://github.com/cct-datascience/ggplot2-workshop-series"
  repo-actions: ["source", "issue"]
  page-footer:
    border: false
    center: |
      [![License: CC BY 4.0](https://img.shields.io/badge/License-CC_BY_4.0-lightgrey.svg)](https://creativecommons.org/licenses/by/4.0/) | [![](https://zenodo.org/badge/795621206.svg)](https://doi.org/10.5281/zenodo.14907482)
  sidebar: 
    style: "docked"
    search: true
    logo: logo.png
    title: "Data Science Team"
    contents:
      - section: "2024"
        href: "2024/index.qmd"
        contents:
          - text: "Session 1 - Foundations"
            href: "2024/01-foundations/index.qmd"
          - text: "Session 2 - Data Communication"
            href: "2024/02-data-comm/index.qmd"
          - text: "Session 3 - Extensions"
            href: "2024/03-extensions/index.qmd"
      - section: "2023"
        contents:
          - text: "Session 1 - Foundations"
            href: "2023/01-foundations/index.qmd"
          - text: "Session 2 - Customizations"
            href: "2023/02-publication-quality-figs/index.qmd"
          - text: "Session 3 - Extensions"
            href: "2023/03-extensions/index.qmd"

format:
  html: 
  #defaults for all html
    code-link: true
    code-copy: true
  uaz-revealjs:
   #defaults for all uaz-revealjs slides
    code-copy: true
    slide-number: true
    chalkboard: true
    mouse-wheel: false
    link-external-icon: true
    link-external-newwindow: true
    logo: "./logo.png"
    footer: "[Intermediate ggplot2 workshop series](index.qmd)"
    
execute:
  freeze: auto
  
editor: 
  markdown: 
    wrap: sentence
  