project: 
  type: website
  
website:
  title: "Unlocking the next level of `ggplot2` (working title)"
  sidebar: 
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "2023"